config/routes.rb
Hicube::Engine.routes.draw do
  
  root 'hicube/pages#show'

  devise_for :users,
    class_name: 'Hicube::User',
    path:        '',
    path_prefix: nil,
    failure_app: 'Hicube::Devise::FailureApp',
    module:      :devise

  resources :pages do
    resources :contents
  end

  resources :snippets
  
  resources :documents

  resource :tag

  resources :accounts
end

Rails.application.routes.draw do

  root 'hicube/public/pages#show', id: 'index'

  get ':id', to: 'hicube/public/pages#show', only: [:show]
  get ':id/edit', to: 'hicube/public/pages#edit', only: [:edit]
  post 'mail', to: 'hicube/public/pages#mail', only: [:mail]
  # get '/',        to: 'hicube/pages#show'
  # match '*path'   => 'hicube/pages#show', via: :all

  namespace :public do
    resources :pages, only: [:show, :edit]
  end

  get 'hicube/public/pages/:id', to: redirect('/%{id}')
end

app/models/hicube/account.rb
module Hicube
  class Account
    
    include Mongoid::Document
    include Mongoid::Timestamps

    # Associations
    #
    has_many :pages, class_name: 'Hicube::Page'
    has_many :snippets, class_name: 'Hicube::Snippet'
    has_many :documents, class_name: 'Hicube::Document'
    has_many :tags, class_name: 'Hicube::Tag'

    #
    # Fields
    #
    field :ga, type: String

    field :notify_email_text, type: String

    field :notify_email_html, type: String

    field :domain, type: String

    validates_presence_of :ga, :domain #, :notify_email_html, :notify_email_text
    validates_uniqueness_of :domain

  end
end

app/controllers/hicube/accounts_controller.rb
require_dependency "hicube/application_controller"

module Hicube
  class AccountsController < BaseController

    before_action :load_resource, except: [
      :create,
      :index,
      :new
    ]

    before_filter :load_resources, :only => [
      :index,
    ]

    # Must be called after load_recource filter.
    before_filter :check_resource_params, :only => [
      :create,
      :update,
    ]

    def create
      @account = Hicube::Account.new(accounts_params)
      @account.save!

      Hicube::Page.create!(title: 'Index', body: 'Add Content here', account: @account, order: 0)

      respond_to do |format|
        notify :notice, ::I18n.t('messages.resource.created',
          :type       => Hicube::Account.model_name.human,
          :resource   => @account
        )
        format.html { redirect_to ('http://' + @account.domain + '/hicube/pages/index/edit'), status: '301' }
      end
    rescue Mongoid::Errors::Validations => e
      respond_to do |format|
        notify_now :error, ::I18n.t('messages.resource.not_valid',
          :type     => Hicube::Account.model_name.human,
          :errors   => @account.errors.full_messages.to_sentence
        )
        format.html { render :action => :new, :status => 422 }
      end
    end

    def update
      @account.update_attributes(accounts_params)
      @account.save!

      notify :notice, ::I18n.t('messages.resource.updated',
        :type       => Hicube::Account.model_name.human,
        :resource   => @account
      )
      render action: :show, id: @account
    rescue Mongoid::Errors::Validations => e
      notify_now :error, ::I18n.t('messages.resource.not_valid',
        :type     => Hicube::Account.model_name.human,
        :errors   => @account.errors.full_messages.to_sentence
      )
      render :action => :edit
    end

    private

    def accounts_params
      params.require(:account).permit(:ga, :domain, :notify_email_html, :notify_email_text)
    end
  end
end

app/controllers/hicube/application_controller.rb
module Hicube
  class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_devise_permitted_params

    #around_filter :audit_trail
    before_filter :initialise_locale

    before_filter :initialise_account_settings

    helper :all 
    
    helper_method :app_name

    #
    # Constants
    #

    FLASH_TYPES = [
      :debug,
      :error,
      :notice,
      :alert,
      :success,
      :warning,
    ]

    #
    # Public Class Methods
    #
    public

    #
    # Public Instance Methods
    #
    public

    def after_sign_in_path_for(resource)
      return request.env['omniauth.origin'] || stored_location_for(resource) || '/hicube/pages/index/edit'
    end

    # Generate a notification message.
    def notify(type, message, options = {})
      options[:now] ||= false

      # Convert and cleanup.
      type = type.to_s.downcase.to_sym

      # Sanity check for type.
      unless FLASH_TYPES.include?(type)
        raise ArgumentError, "Invalid value for argument type: #{type}, expected one of: #{FLASH_TYPES.to_sentence}."
      end

      logger.info("FLASH (#{options.inspect}) #{type.to_s.upcase}: #{message}")

      if options[:now] == true
        flash.now[type] ||= []
        flash.now[type] << message
      else
        flash[type] ||= []
        flash[type] << message
      end

      logger.debug("DEBUG: FLASH #{flash.inspect}")

      return true
    end

    def notify_now(type, message, options = {})
      options[:now] = true
      notify(type, message, options)
    end

    #
    # Protected Instance Methods
    #
    protected

    #
    # Private Instance Methods
    #
    private

    def app_name
      t('app.name') || Rails.application.class.to_s.split("::").first 
    end

    def action_controller_helpers
      return ActionController::Base.helpers
    end

    def audit_trail
      # Create a shallow copy only so be careful.
      local_params = params.clone

      # Strip out redundant, useless or other unwanted parameters.
      local_params.reject!{ |k,v| %w(action authenticity_token eid controller).include?(k) }

      # Filter sensitive and/or useless parameters.
      %w(password password_confirmation).each do |k|
        local_params[k] = '***' if local_params.has_key?(k)
      end

      # Filter sensitive and/or useless parameters.
      %w(user).each do |j|
        if local_params.has_key?(j)
          local_params[j] = local_params[j].clone
          %w(password password_confirmation).each do |k|
            local_params[j][k] = '***' if local_params[j].has_key?(k)
          end
        end
      end

      # Create an audit trail for the request.
      # AUDIT_LOG.info("ACCESS") { "REQUEST::#{request.method}::#{params[:controller]}##{params[:action]}::#{request.remote_ip}::#{request.fullpath.split('?')[0]}::#{local_params.inspect}" }

      # Proceed as normal.
      yield

      # Create an audit trail for the response.
      # AUDIT_LOG.info("ACCESS") { "RESPONSE::#{request.method}::#{params[:controller]}##{params[:action]}::#{response.status}::#{response.content_type}::#{response.location || '-'}" }

    rescue => e
      # Log the exception and then re-raise so it can be handled as normal.
      # AUDIT_LOG.error("EXCEPTION") { "#{request.remote_ip}::#{request.method}::#{params[:controller]}##{params[:action]}::#{e.class.to_s}::#{e.message}::#{e.backtrace[0...5]}" }
      raise
    end

    def initialise_account_settings
      Rails.application.configure do 
        GA.tracker = Hicube::Account.first.ga unless Hicube::Account.first.nil? or Hicube::Account.first.ga.nil?
      end if Rails.env.production? or Rails.env.staging?
    end

    def initialise_locale
      # if params[:locale] is nil then I18n.default_locale will be used.
      I18n.locale = params[:locale]
    end

    def respond(http_status, response, options = {})
      respond_to do |format|
        format.json { render json: response, status: http_status }
        format.xml  { render xml:  response, root: :response, status: http_status }
      end
    end

    def respond_with_success(options = {})
      http_status = options[:http_status] || :ok

      response = {}
      response[:status] = options[:status] || 'OK'
      response.merge!(options[:response]) if options.has_key?(:response)

      respond(http_status, response)
    end

    def respond_with_error(http_status, options = {})
      response = {}
      response[:status] = options[:status] || 'ERROR'
      response[:error] = {}
      response[:error][:code] = options[:code] || http_status.to_s.dasherize
      response[:error][:message] = options[:message]
      response.merge!(options[:response]) if options.has_key?(:response)

      respond(http_status, response)
    end

    protected

    def configure_devise_permitted_params
      unless params
        devise_parameter_sanitizer.for(:sign_up) << :name if params[:controller].include? 'devise'
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email) } if params[:controller].include? 'devise'
      end
    end

  end
end

app/controllers/hicube/base_controller.rb
module Hicube
  class BaseController < Hicube::ApplicationController

    # Skip the before filter so we can insert it in the correctly place to preserve order.
    # skip_around_filter :audit_trail

    before_action :authenticate_user!
    before_filter :initialise_current_user

    # around_filter :audit_trail
    helper_method :current_account

    # layout 'application'


    #
    # Private Instance Methods
    #
    private

    def initialise_current_user
      return unless user_signed_in?
      User.current = current_user
    end

    def current_account
      Hicube::Account.find_by(domain: request.host_with_port)
    end

    # Check resource params are present based on the current controller name.
    def check_resource_params(options = {})

      # Determine the name based on the current controller if not specified.
      resource_name = options[:name] || controller_name.singularize

      # Determine the class based on the resource name if not provided.
      #FIXME: Do not hardcode engine name
      resource_class = options[:class] || "Hicube::#{resource_name.singularize.camelize}".classify.constantize
      

      unless params.key?(resource_name)
        notify :error, ::I18n.t('messages.resource.missing_parameters',
          :type     => resource_class.model_name.human
        )

        case action_name.to_sym
        when :create
          redirect_to :action => :new
        when :update
          redirect_to :action => :edit, :id => params[:id]
        else
          redirect_to :action => :index
        end
      end
    end

    # Load the relevant resource based on the current controller name.
    def load_resource(options = {})

      # Determine the name based on the current controller if not specified.
      resource_name = options[:name] || controller_name.singularize

      # Determine the class based on the resource name if not provided.
      # FIXME: Do not hard code engine name 
      resource_class = options[:class] || "Hicube::#{resource_name.singularize.camelize}".classify.constantize

      resource = if resource_class == Hicube::Account
        # resource = Hicube::Account.first
        current_account
      else
        # resource = resource_class.unscoped.find(params[:id])
        resource_class.unscoped.where(account: current_account).find(params[:id])
      end
      # # Confirm current user has permission to view resource.
      # unless resource.account == current_account
      #   # TODO: log an audit event.

      #   # SECURITY RISK: The user should not be able to distinguish between a
      #   # non-existant resource and another user's resource. This way you can't
      #   # probe to the system and determine another account's data.
      #   raise Mongoid::Errors::DocumentNotFound.new(resource_class, :id => params[:id])
      # end

      # Set an instance variable @resource_name to the resource.
      instance_variable_set("@#{resource_name}", resource)

      rescue Mongoid::Errors::DocumentNotFound => e
      notify :error, ::I18n.t('messages.resource.not_found',
        :type     => resource_class.model_name.human,
        :criteria => resource_class.human_attribute_name(:id),
        :value    => params[:id]
      )
      redirect_to :action => :index
    end

    # Load all relevant resources based on the current controller name.
    def load_resources(options = {})

      # Determine the name based on the current controller if not specified.
      resource_name = options[:name] || controller_name.pluralize

      # Set an instance variable @name to contain the names for this user.
      #FIXME: Do not hard code Hicube here
      instance_variable_set("@#{resource_name}", "Hicube::#{resource_name.singularize.camelize}".classify.constantize.unscoped.where(account: current_account).all)
    end

    # def setup_account!
    #   case 
    #   when current_user.account.nil?
    #     if current_user.sign_in_count == 1
    #       logger.debug "Account not present, first login so show edit account page."
    #       notify :success, "Almost done! Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #       redirect_to new_users_settings_account_path # if current_user.account.nil?
    #     else
    #       logger.debug "Account not present, returning user so show edit account page."
    #       notify :warning, "Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #       redirect_to (current_user.account.nil? ? new_users_settings_account_path : edit_users_settings_account_path) # if current_user.account.nil?
    #     end
    #   when Subscriber.by_account(current_user.account).count > current_user.account.allowance
    #     logger.debug "Allowance Breached. Current allowance = #{current_user.account.allowance} & Subscriber count = #{Subscriber.by_account(current_user.account).count}"
    #     notify :error, "You have more subscribers in your database than allowed under your plan. Please update subscription before proceeding."
    #     redirect_to edit_users_settings_account_path # if current_user.account.nil?
    #   end
    

    #   # if current_user.account.nil? or (Subscriber.by_account(current_user.account).count > current_user.account.allowance)
    #   #   if current_user.sign_in_count == 1
    #   #     notify :success, "Almost done! Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #   #     redirect_to new_users_settings_account_path # if current_user.account.nil?
    #   #   elsif Subscriber.by_account(current_user.account).count > current_user.account.allowance
    #   #     notify :error, "You have more subscribers in your database than allowed under your plan. Please update subscription before proceeding."
    #   #     redirect_to edit_users_settings_account_path # if current_user.account.nil?
    #   #   else
    #   #     notify :warning, "Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #   #     redirect_to edit_users_settings_account_path # if current_user.account.nil?
    #   #   end
        
    #   # end
    # end

    # FIXME: CSRF token authenticity should not be overridden for JSON anymore in Rails 4?
    # This is to avoid warning - Can't verify CSRF token authenticity.
    # def verified_request?
    #   if request.content_type == "application/json"
    #     true
    #   else
    #     super()
    #   end
    # end

  end
end

app/helpers/hicube/application_helper.rb
module Hicube
  module ApplicationHelper

    def heading
      if current_page?(action: :new)
        'New'
      else
        instance_variable_get("@#{controller_name.singularize}") || controller_name.camelize
      end
    end

    def subheading
      return if controller_name.eql?('dashboards')
      controller_name.singularize.camelize unless current_page?(action: :index)
    end

    def breadcrumbs
      return [] if controller_name.eql?('dashboards')
      case
      when current_page?(action: :index)
        { controller_name.camelize => {path: nil, active: true} }
      when current_page?(action: :new)
        {
          controller_name.camelize => {path: url_for(controller: controller_name, action: :index), active: false},
          'New' => {path: nil, active: true}
        }
      else # show & edit
        {
          controller_name.camelize => {path: url_for(controller: controller_name, action: :index), active: false},
          instance_variable_get("@#{controller_name.singularize}") => {path: nil, active: true}
        }
      end
    end

    def sidebar_class(action, model, options = {})
      case action
      when :edit, :new
        if options.nil?
          current_page?(eval("#{action}_#{model}_path")) ? :active : nil rescue nil # for edit
        else
          current_page?(eval("#{action}_#{model}_path(options)")) ? :active : nil rescue nil # for edit
        end
      when :index
        current_page?(eval("#{model.to_s.pluralize}_path")) ? :active : nil
      when :show
        if options.nil?
          current_page?(eval("#{model}_path")) ? :active : nil rescue nil
        else
          current_page?(eval("#{model}_path(options)")) ? :active : nil rescue nil
        end        
      else
        nil
      end
    end

    def root_path
      '/'
    end

    def snippet_render(name)
      snippet = Hicube::Snippet.find_by(name: name)
      raw "#{Hicube::Markdown.render(::Liquid::Template.parse(snippet.body).render).html_safe}"
    rescue Mongoid::Errors::DocumentNotFound => dnf
      raw "Snippet Not found with name #{name}"
    rescue Exception => e
      raw "#{e}"
    end

  end
end

app/helpers/hicube/contents_helper.rb
module Hicube
  module ContentsHelper
  end
end

app/helpers/hicube/documents_helper.rb
module Hicube
  module DocumentsHelper
  end
end

app/helpers/hicube/pages_helper.rb
module Hicube
  module PagesHelper
  end
end

app/helpers/hicube/snippets_helper.rb
module Hicube
  module SnippetsHelper
  end
end

app/views/hicube/pages/_form.html.slim
/ .row    
/   .col-xs-12
/     .box.box-warning class=(current_page?(new_page_path) ? 'expanded-box' : 'collapsed-box')
/       .box-header.with-border
/         h3.box-title Page Details
/         .box-tools.pull-right
/           button.btn.btn-box-tool[data-widget="collapse"]
/             i.fa.fa-plus
/       .box-body
/         .row
/           .col-xs-8
/             = f.label :name
/             = f.text_field :title, placeholder: 'Enter ...', disabled: (@page.title.eql?('Index') rescue false), class: 'form-control'
/           .col-xs-4
/             = f.label :parent
/             = f.collection_select :parent, Hicube::Page.parents,:id,:title,{include_blank: '', selected: parent_id},{class: 'form-control', disabled: (@page.title.eql?('Index') rescue false)}
/         br
/         .form-group
/           = f.label :seo_title
/           = f.text_field :seo_title, class: 'form-control'
/         .form-group
/           = f.label :seo_keywords
/           = f.text_field :seo_keywords, class: 'form-control'
/         .form-group
/           = f.label :seo_description
/           = f.text_field :seo_description, class: 'form-control'
        
/         - unless current_page?(new_page_path) or @page.content.empty?
/           strong
/             | Additional Tags
/           br
/           = f.fields_for :content, @page.content do |c|
/             - if c.object.head
/               .row
/                 = c.hidden_field :head, value: '1'
/                 .col-xs-3
/                   = c.text_field :name, class: 'form-control'
/                 .col-xs-8
/                   = c.text_field :body, class: 'form-control'
/                 .col-xs-1
/                   = c.check_box :_destroy, class: 'minimal'
/                   |  Delete
/           br
/         button#add-tag.btn.btn-default[type="button"] Add Additional Tag
/         #tag-form style="display: none;"
/           = f.fields_for :content, Hicube::Content.new do |c|
/             .row
/               = c.hidden_field :head, value: '1'
/               .col-xs-3
/                 = c.text_field :name, placeholder: 'Name', class: 'form-control'
/               .col-xs-8
/                 = c.text_field :body, placeholder: 'Content', class: 'form-control'
/               .col-xs-1
/                   = c.check_box :_destroy, class: 'minimal'
/                   |  Delete

/ - if current_page?(new_page_path)
/   .form-group
/     = f.label :body
/     - if current_page?(new_page_path)
/       = f.text_area :body, id: "textarea", value: "\n\n\n\n\n\n\n", class: 'form-control'
/     - else
/       = f.text_area :body, id: "textarea", class: 'form-control'
/ - else
.row
  .col-xs-12
    .nav-tabs-custom
      ul.nav.nav-tabs
        li class=(@page.nil? || @page.new_record? ? 'active' : nil)
          a[href="#details" data-toggle="tab"]
            | Details
        - unless @page.nil? || @page.new_record 
          li
            a[href="#wysiwig" data-toggle="tab"]
              | WYSIWIG
        li class=(@page.nil? || @page.new_record ? '' : 'active')
          a[href="#raw" data-toggle="tab"]
            | Raw Content
        
      .tab-content
        - if @page.nil? || @page.new_record? || current_page?(new_page_path)
          #raw.tab-pane
            = f.text_area :body, id: "textarea", value: "Add content here", class: 'form-control .codeMirror'
        - else
          #raw.tab-pane.active
            = f.text_area :body, id: "textarea", class: 'form-control .codeMirror'

        / #raw.tab-pane class=( ? '' : 'active')
        /   = f.text_area :body, id: "textarea", value: "\n\n\n\n\n\n\n", class: 'form-control .codeMirror'
        - unless current_page?(new_page_path) 
          #wysiwig.tab-pane
            iframe src="/#{@page.slug}/edit" width="100%" height="100%" frameBorder=0 style="height: 100vh"
        #details.tab-pane class=(@page.nil? || @page.new_record? || current_page?(new_page_path) ? 'active' : nil)
          .row
            .col-xs-3
              = f.label :name
              = f.text_field :title, placeholder: 'Enter ...', disabled: (@page.index? rescue false), class: 'form-control'
            .col-xs-3
              = f.label :parent
              = f.collection_select :parent, current_account.pages.parents.where(:id.ne => (@page.nil? ? '' : @page.id)),:id,:title,{include_blank: '', selected: parent_id},{class: 'form-control', disabled: (@page.index? rescue false)}
            .col-xs-2
              = f.label :link_order
              = f.select :order, 1..Hicube::Page.count, {}, {disabled: (@page.index? rescue false), class: 'form-control'}
            .col-xs-2
              .checkbox.iCheck style="padding-top: 10px;"
              label= f.check_box :header, class: 'minimal'
              strong
                |  Appear in Header
            .col-xs-2
              .checkbox.iCheck style="padding-top: 10px;"
              label= f.check_box :footer, class: 'minimal'
              strong
                |  Appear in Footer

          br
          .form-group
            = f.label :seo_title
            = f.text_field :seo_title, class: 'form-control'
          .form-group
            = f.label :seo_keywords
            = f.text_field :seo_keywords, class: 'form-control'
          .form-group
            = f.label :seo_description
            = f.text_field :seo_description, class: 'form-control'
          
          - unless current_page?(new_page_path) or @page.content.empty?
            strong
              | Additional Tags
            br
            = f.fields_for :content, @page.content do |c|
              - if c.object.head
                .row
                  = c.hidden_field :head, value: '1'
                  .col-xs-3
                    = c.text_field :name, class: 'form-control'
                  .col-xs-8
                    = c.text_field :body, class: 'form-control'
                  .col-xs-1
                    = c.check_box :_destroy, class: 'minimal'
                    |  Delete
            br
          button#add-tag.btn.btn-default[type="button"] Add Additional Tag
          #tag-form style="display: none;"
            = f.fields_for :content, Hicube::Content.new do |c|
              .row
                = c.hidden_field :head, value: '1'
                .col-xs-3
                  = c.text_field :name, placeholder: 'Name', class: 'form-control'
                .col-xs-8
                  = c.text_field :body, placeholder: 'Content', class: 'form-control'
                .col-xs-1
                    = c.check_box :_destroy, class: 'minimal'
                    |  Delete

app/views/hicube/pages/_navigation.html.slim
- if current_page?(action: 'new')
  - heading = 'New'
  - subheading = 'Page'
- elsif current_page?(action: 'index')
  - heading = 'Pages'
  - subheading = 'All'
- elsif current_page?(action: 'edit')
  - heading = "#{@page}"
  - subheading = 'Edit'

section.content-header
  h1
    / | #{heading} #{(current_page?(action: 'index') ? controller_name.camelize : controller_name.singularize.camelize)}
    | #{heading}
    small
      | #{subheading}
  ol.breadcrumb
    li
      a href=pages_path
        i.fa.fa-dashboard
        |  Home
    li class=(current_page?(eval("#{controller_name}_path")) ? :active : nil)
      a href="#{controller_name}_path"
        = controller_name.camelize
    - unless current_page?(eval("#{controller_name}_path"))
      li.active
        | #{heading}

app/views/hicube/pages/edit.html.slim
section.content
  = form_for @page, as: :page, url: page_path(@page), role: 'form' do |f|
    .box.no-border
      .box-body
        = render partial: 'form', locals: { f: f, parent_id: ((@page.present? and !@page.parent.nil?) ? @page.parent.id.to_s : '')}
      .box-footer.no-border
        button.btn.btn-flat.btn-primary.pull-right[type="submit"]
          | Save
        = link_to 'Delete', page_path(@page), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-flat btn-danger'

app/views/hicube/pages/index.html.slim
section.content
  .row
    .col-md-12
      .box
        .box-body.table-responsive
          table#datatable.table.table-bordered.table-striped
            thead
              tr
                th
                  .col-md-11
                    = Hicube::Page.human_attribute_name(:title)
                  .col-md-1
            tbody
              - @pages.parents.each do |p|
                tr 
                  td
                    .col-md-11
                      = p.title
                    .col-md-1
                      = link_to t('edit'), edit_page_path(p), class: 'btn btn-sm btn-primary'
                - p.children.each do |child|
                  tr  
                    td
                      .col-xs-11
                        | &nbsp;          
                        i.fa.fa-angle-double-right
                        '   
                        = child.title
                      .col-xs-1
                        = link_to t('edit'), edit_page_path(child), class: 'btn btn-sm btn-primary'                
        .box-footer
          = link_to 'New Page', new_page_path, class: 'btn btn-flat btn-success pull-right'

app/views/hicube/pages/new.html.slim
section.content
  = form_for :page, url: pages_path, role: 'form' do |f|
    .box.no-border
      .box-body
        = render partial: 'form', locals: { f: f, parent_id: ((@page.present? and @page.junction?) ? @page.parent.id : '') }
      .box-footer.no-border
        button.btn.btn-flat.btn-primary.pull-right[type="submit"]
          | Submit 
        = link_to 'Cancel', pages_path, class: 'btn btn-flat btn-default'

app/views/hicube/pages/show.html.slim
/ section.content.invoice
/   iframe#rails_iframe height="100%" src=page_path(@page) frameborder="0" width="100%"