config/routes.rb
Hicube::Engine.routes.draw do
  
  root 'hicube/pages#show'

  devise_for :users,
    class_name: 'Hicube::User',
    path:        '',
    path_prefix: nil,
    failure_app: 'Hicube::Devise::FailureApp',
    module:      :devise

  resources :pages do
    resources :contents
  end

  resources :snippets
  
  resources :documents

  resource :tag

  resources :accounts
end

Rails.application.routes.draw do

  root 'hicube/public/pages#show', id: 'index'

  get ':id', to: 'hicube/public/pages#show', only: [:show]
  get ':id/edit', to: 'hicube/public/pages#edit', only: [:edit]
  post 'mail', to: 'hicube/public/pages#mail', only: [:mail]
  # get '/',        to: 'hicube/pages#show'
  # match '*path'   => 'hicube/pages#show', via: :all

  namespace :public do
    resources :pages, only: [:show, :edit]
  end

  get 'hicube/public/pages/:id', to: redirect('/%{id}')
end

app/models/hicube/account.rb
module Hicube
  class Account
    
    include Mongoid::Document
    include Mongoid::Timestamps

    # Associations
    #
    has_many :pages, class_name: 'Hicube::Page'
    has_many :snippets, class_name: 'Hicube::Snippet'
    has_many :documents, class_name: 'Hicube::Document'
    has_many :tags, class_name: 'Hicube::Tag'

    #
    # Fields
    #
    field :ga, type: String

    field :notify_email_text, type: String

    field :notify_email_html, type: String

    field :domain, type: String

    validates_presence_of :ga, :domain #, :notify_email_html, :notify_email_text
    validates_uniqueness_of :domain

  end
end

app/controllers/hicube/accounts_controller.rb
require_dependency "hicube/application_controller"

module Hicube
  class AccountsController < BaseController

    before_action :load_resource, except: [
      :create,
      :index,
      :new
    ]

    before_filter :load_resources, :only => [
      :index,
    ]

    # Must be called after load_recource filter.
    before_filter :check_resource_params, :only => [
      :create,
      :update,
    ]

    def create
      @account = Hicube::Account.new(accounts_params)
      @account.save!

      Hicube::Page.create!(title: 'Index', body: 'Add Content here', account: @account, order: 0)

      respond_to do |format|
        notify :notice, ::I18n.t('messages.resource.created',
          :type       => Hicube::Account.model_name.human,
          :resource   => @account
        )
        format.html { redirect_to ('http://' + @account.domain + '/hicube/pages/index/edit'), status: '301' }
      end
    rescue Mongoid::Errors::Validations => e
      respond_to do |format|
        notify_now :error, ::I18n.t('messages.resource.not_valid',
          :type     => Hicube::Account.model_name.human,
          :errors   => @account.errors.full_messages.to_sentence
        )
        format.html { render :action => :new, :status => 422 }
      end
    end

    def update
      @account.update_attributes(accounts_params)
      @account.save!

      notify :notice, ::I18n.t('messages.resource.updated',
        :type       => Hicube::Account.model_name.human,
        :resource   => @account
      )
      render action: :show, id: @account
    rescue Mongoid::Errors::Validations => e
      notify_now :error, ::I18n.t('messages.resource.not_valid',
        :type     => Hicube::Account.model_name.human,
        :errors   => @account.errors.full_messages.to_sentence
      )
      render :action => :edit
    end

    private

    def accounts_params
      params.require(:account).permit(:ga, :domain, :notify_email_html, :notify_email_text)
    end
  end
end

app/controllers/hicube/application_controller.rb
module Hicube
  class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_devise_permitted_params

    #around_filter :audit_trail
    before_filter :initialise_locale

    before_filter :initialise_account_settings

    helper :all 
    
    helper_method :app_name

    #
    # Constants
    #

    FLASH_TYPES = [
      :debug,
      :error,
      :notice,
      :alert,
      :success,
      :warning,
    ]

    #
    # Public Class Methods
    #
    public

    #
    # Public Instance Methods
    #
    public

    def after_sign_in_path_for(resource)
      return request.env['omniauth.origin'] || stored_location_for(resource) || '/hicube/pages/index/edit'
    end

    # Generate a notification message.
    def notify(type, message, options = {})
      options[:now] ||= false

      # Convert and cleanup.
      type = type.to_s.downcase.to_sym

      # Sanity check for type.
      unless FLASH_TYPES.include?(type)
        raise ArgumentError, "Invalid value for argument type: #{type}, expected one of: #{FLASH_TYPES.to_sentence}."
      end

      logger.info("FLASH (#{options.inspect}) #{type.to_s.upcase}: #{message}")

      if options[:now] == true
        flash.now[type] ||= []
        flash.now[type] << message
      else
        flash[type] ||= []
        flash[type] << message
      end

      logger.debug("DEBUG: FLASH #{flash.inspect}")

      return true
    end

    def notify_now(type, message, options = {})
      options[:now] = true
      notify(type, message, options)
    end

    #
    # Protected Instance Methods
    #
    protected

    #
    # Private Instance Methods
    #
    private

    def app_name
      t('app.name') || Rails.application.class.to_s.split("::").first 
    end

    def action_controller_helpers
      return ActionController::Base.helpers
    end

    def audit_trail
      # Create a shallow copy only so be careful.
      local_params = params.clone

      # Strip out redundant, useless or other unwanted parameters.
      local_params.reject!{ |k,v| %w(action authenticity_token eid controller).include?(k) }

      # Filter sensitive and/or useless parameters.
      %w(password password_confirmation).each do |k|
        local_params[k] = '***' if local_params.has_key?(k)
      end

      # Filter sensitive and/or useless parameters.
      %w(user).each do |j|
        if local_params.has_key?(j)
          local_params[j] = local_params[j].clone
          %w(password password_confirmation).each do |k|
            local_params[j][k] = '***' if local_params[j].has_key?(k)
          end
        end
      end

      # Create an audit trail for the request.
      # AUDIT_LOG.info("ACCESS") { "REQUEST::#{request.method}::#{params[:controller]}##{params[:action]}::#{request.remote_ip}::#{request.fullpath.split('?')[0]}::#{local_params.inspect}" }

      # Proceed as normal.
      yield

      # Create an audit trail for the response.
      # AUDIT_LOG.info("ACCESS") { "RESPONSE::#{request.method}::#{params[:controller]}##{params[:action]}::#{response.status}::#{response.content_type}::#{response.location || '-'}" }

    rescue => e
      # Log the exception and then re-raise so it can be handled as normal.
      # AUDIT_LOG.error("EXCEPTION") { "#{request.remote_ip}::#{request.method}::#{params[:controller]}##{params[:action]}::#{e.class.to_s}::#{e.message}::#{e.backtrace[0...5]}" }
      raise
    end

    def initialise_account_settings
      Rails.application.configure do 
        GA.tracker = Hicube::Account.first.ga unless Hicube::Account.first.nil? or Hicube::Account.first.ga.nil?
      end if Rails.env.production? or Rails.env.staging?
    end

    def initialise_locale
      # if params[:locale] is nil then I18n.default_locale will be used.
      I18n.locale = params[:locale]
    end

    def respond(http_status, response, options = {})
      respond_to do |format|
        format.json { render json: response, status: http_status }
        format.xml  { render xml:  response, root: :response, status: http_status }
      end
    end

    def respond_with_success(options = {})
      http_status = options[:http_status] || :ok

      response = {}
      response[:status] = options[:status] || 'OK'
      response.merge!(options[:response]) if options.has_key?(:response)

      respond(http_status, response)
    end

    def respond_with_error(http_status, options = {})
      response = {}
      response[:status] = options[:status] || 'ERROR'
      response[:error] = {}
      response[:error][:code] = options[:code] || http_status.to_s.dasherize
      response[:error][:message] = options[:message]
      response.merge!(options[:response]) if options.has_key?(:response)

      respond(http_status, response)
    end

    protected

    def configure_devise_permitted_params
      unless params
        devise_parameter_sanitizer.for(:sign_up) << :name if params[:controller].include? 'devise'
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email) } if params[:controller].include? 'devise'
      end
    end

  end
end

app/controllers/hicube/base_controller.rb
module Hicube
  class BaseController < Hicube::ApplicationController

    # Skip the before filter so we can insert it in the correctly place to preserve order.
    # skip_around_filter :audit_trail

    before_action :authenticate_user!
    before_filter :initialise_current_user

    # around_filter :audit_trail
    helper_method :current_account

    # layout 'application'


    #
    # Private Instance Methods
    #
    private

    def initialise_current_user
      return unless user_signed_in?
      User.current = current_user
    end

    def current_account
      Hicube::Account.find_by(domain: request.host_with_port)
    end

    # Check resource params are present based on the current controller name.
    def check_resource_params(options = {})

      # Determine the name based on the current controller if not specified.
      resource_name = options[:name] || controller_name.singularize

      # Determine the class based on the resource name if not provided.
      #FIXME: Do not hardcode engine name
      resource_class = options[:class] || "Hicube::#{resource_name.singularize.camelize}".classify.constantize
      

      unless params.key?(resource_name)
        notify :error, ::I18n.t('messages.resource.missing_parameters',
          :type     => resource_class.model_name.human
        )

        case action_name.to_sym
        when :create
          redirect_to :action => :new
        when :update
          redirect_to :action => :edit, :id => params[:id]
        else
          redirect_to :action => :index
        end
      end
    end

    # Load the relevant resource based on the current controller name.
    def load_resource(options = {})

      # Determine the name based on the current controller if not specified.
      resource_name = options[:name] || controller_name.singularize

      # Determine the class based on the resource name if not provided.
      # FIXME: Do not hard code engine name 
      resource_class = options[:class] || "Hicube::#{resource_name.singularize.camelize}".classify.constantize

      resource = if resource_class == Hicube::Account
        # resource = Hicube::Account.first
        current_account
      else
        # resource = resource_class.unscoped.find(params[:id])
        resource_class.unscoped.where(account: current_account).find(params[:id])
      end
      # # Confirm current user has permission to view resource.
      # unless resource.account == current_account
      #   # TODO: log an audit event.

      #   # SECURITY RISK: The user should not be able to distinguish between a
      #   # non-existant resource and another user's resource. This way you can't
      #   # probe to the system and determine another account's data.
      #   raise Mongoid::Errors::DocumentNotFound.new(resource_class, :id => params[:id])
      # end

      # Set an instance variable @resource_name to the resource.
      instance_variable_set("@#{resource_name}", resource)

      rescue Mongoid::Errors::DocumentNotFound => e
      notify :error, ::I18n.t('messages.resource.not_found',
        :type     => resource_class.model_name.human,
        :criteria => resource_class.human_attribute_name(:id),
        :value    => params[:id]
      )
      redirect_to :action => :index
    end

    # Load all relevant resources based on the current controller name.
    def load_resources(options = {})

      # Determine the name based on the current controller if not specified.
      resource_name = options[:name] || controller_name.pluralize

      # Set an instance variable @name to contain the names for this user.
      #FIXME: Do not hard code Hicube here
      instance_variable_set("@#{resource_name}", "Hicube::#{resource_name.singularize.camelize}".classify.constantize.unscoped.where(account: current_account).all)
    end

    # def setup_account!
    #   case 
    #   when current_user.account.nil?
    #     if current_user.sign_in_count == 1
    #       logger.debug "Account not present, first login so show edit account page."
    #       notify :success, "Almost done! Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #       redirect_to new_users_settings_account_path # if current_user.account.nil?
    #     else
    #       logger.debug "Account not present, returning user so show edit account page."
    #       notify :warning, "Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #       redirect_to (current_user.account.nil? ? new_users_settings_account_path : edit_users_settings_account_path) # if current_user.account.nil?
    #     end
    #   when Subscriber.by_account(current_user.account).count > current_user.account.allowance
    #     logger.debug "Allowance Breached. Current allowance = #{current_user.account.allowance} & Subscriber count = #{Subscriber.by_account(current_user.account).count}"
    #     notify :error, "You have more subscribers in your database than allowed under your plan. Please update subscription before proceeding."
    #     redirect_to edit_users_settings_account_path # if current_user.account.nil?
    #   end
    

    #   # if current_user.account.nil? or (Subscriber.by_account(current_user.account).count > current_user.account.allowance)
    #   #   if current_user.sign_in_count == 1
    #   #     notify :success, "Almost done! Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #   #     redirect_to new_users_settings_account_path # if current_user.account.nil?
    #   #   elsif Subscriber.by_account(current_user.account).count > current_user.account.allowance
    #   #     notify :error, "You have more subscribers in your database than allowed under your plan. Please update subscription before proceeding."
    #   #     redirect_to edit_users_settings_account_path # if current_user.account.nil?
    #   #   else
    #   #     notify :warning, "Please complete #{Account.model_name.human.downcase} setup before proceeding."
    #   #     redirect_to edit_users_settings_account_path # if current_user.account.nil?
    #   #   end
        
    #   # end
    # end

    # FIXME: CSRF token authenticity should not be overridden for JSON anymore in Rails 4?
    # This is to avoid warning - Can't verify CSRF token authenticity.
    # def verified_request?
    #   if request.content_type == "application/json"
    #     true
    #   else
    #     super()
    #   end
    # end

  end
end

app/helpers/hicube/application_helper.rb
module Hicube
  module ApplicationHelper

    def heading
      if current_page?(action: :new)
        'New'
      else
        instance_variable_get("@#{controller_name.singularize}") || controller_name.camelize
      end
    end

    def subheading
      return if controller_name.eql?('dashboards')
      controller_name.singularize.camelize unless current_page?(action: :index)
    end

    def breadcrumbs
      return [] if controller_name.eql?('dashboards')
      case
      when current_page?(action: :index)
        { controller_name.camelize => {path: nil, active: true} }
      when current_page?(action: :new)
        {
          controller_name.camelize => {path: url_for(controller: controller_name, action: :index), active: false},
          'New' => {path: nil, active: true}
        }
      else # show & edit
        {
          controller_name.camelize => {path: url_for(controller: controller_name, action: :index), active: false},
          instance_variable_get("@#{controller_name.singularize}") => {path: nil, active: true}
        }
      end
    end

    def sidebar_class(action, model, options = {})
      case action
      when :edit, :new
        if options.nil?
          current_page?(eval("#{action}_#{model}_path")) ? :active : nil rescue nil # for edit
        else
          current_page?(eval("#{action}_#{model}_path(options)")) ? :active : nil rescue nil # for edit
        end
      when :index
        current_page?(eval("#{model.to_s.pluralize}_path")) ? :active : nil
      when :show
        if options.nil?
          current_page?(eval("#{model}_path")) ? :active : nil rescue nil
        else
          current_page?(eval("#{model}_path(options)")) ? :active : nil rescue nil
        end        
      else
        nil
      end
    end

    def root_path
      '/'
    end

    def snippet_render(name)
      snippet = Hicube::Snippet.find_by(name: name)
      raw "#{Hicube::Markdown.render(::Liquid::Template.parse(snippet.body).render).html_safe}"
    rescue Mongoid::Errors::DocumentNotFound => dnf
      raw "Snippet Not found with name #{name}"
    rescue Exception => e
      raw "#{e}"
    end

  end
end

app/helpers/hicube/contents_helper.rb
module Hicube
  module ContentsHelper
  end
end

app/helpers/hicube/documents_helper.rb
module Hicube
  module DocumentsHelper
  end
end

app/helpers/hicube/pages_helper.rb
module Hicube
  module PagesHelper
  end
end

app/helpers/hicube/snippets_helper.rb
module Hicube
  module SnippetsHelper
  end
end

app/views/hicube/base/_flash.html.slim
section.content-header
  - unless flash.nil?
    - flash.each do |type, message|
      
      / Skip unknown flash types.
      - next unless Hicube::ApplicationController::FLASH_TYPES.include?(type.to_sym)

      - if type.to_s.downcase == 'success'
        .alert.alert-success.alert-dismissable.fade.in
          button.close data-dismiss="alert" aria-hidden="true"
           ' &times;
          | #{message.join(', ') rescue message}
      - elsif type.to_s.downcase == 'notice'
        .alert.alert-info.alert-dismissable.fade.in
         button.close data-dismiss="alert" aria-hidden="true"
           ' &times;
         | #{message.join(', ') rescue message}
      - elsif type.to_s.downcase == 'alert'
        .alert.alert-danger.alert-dismissable.fade.in
         button.close data-dismiss="alert" aria-hidden="true"
           ' &times;
         | #{message.join(', ') rescue message}
      - elsif type.to_s.downcase == 'error'
        .alert.alert-danger.alert-dismissable.fade.in
          button.close data-dismiss="alert" aria-hidden="true"
           ' &times;
          | #{message.join(', ') rescue message}
      - elsif type.to_s.downcase == 'warning'
        .alert.alert-warning.alert-dismissable.fade.in
          button.close data-dismiss="alert" aria-hidden="true"
           ' &times;
          | #{message.join(', ') rescue message}
      - else
        .alert.alert-info.alert-dismissable.fade.in
          button.close data-dismiss="alert" aria-hidden="true" &times;
          | #{message.join(', ') rescue message}

app/views/hicube/base/_footer.html.slim
.pull-right.hidden-xs
  b
    | Version
  |  1.0 
strong
  | Copyright © 2014-2015 
  a[href="http://www.tecfoundary.com"]
    | Powered By Tecfoundary
  | .
|  All rights reserved. 

app/views/hicube/base/_header.html.slim
header.main-header
  a.logo href=root_path
    b
      = app_name
      / = app_name.gsub(/[a-z]+/, "")
      
  nav.navbar.navbar-static-top[role="navigation"]
    a.sidebar-toggle[href="#" data-toggle="offcanvas" role="button"]
      span.sr-only
        | Toggle navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.user.user-menu
          a.dropdown-toggle href="#" data-toggle="dropdown" aria-expanded="false"
            = image_tag 'avatar.png', alt: 'User Image', class: 'user-image'
            span.hidden-xs
              = current_user.name
          ul.dropdown-menu
            li.user-header
              = image_tag "avatar.png", alt: "User image", class: 'img-circle'
              p
                = current_user.name
                small
                  | Member since #{current_user.created_at}
            li.user-footer
              - if current_user.admin?
                .pull-left
                  - unless Hicube::Account.count > 1
                    = link_to 'New Site', new_account_path, class: 'btn btn-flat btn-default'

              .pull-right
                = link_to destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'
                  | Sign out
        - if current_user.admin?
          li.dropdown.notifications-menu
            a.dropdown-toggle href="#" data-toggle="dropdown" aria-expanded="false"
              i.fa.fa-gears
            ul.dropdown-menu
              li.header
                | You have #{Hicube::Account.count} sites
              li
                ul.menu
                  - Hicube::Account.each do |a|
                    - unless a == current_account
                      li
                        a[href="http://#{a.domain}/hicube/pages/index/edit"]
                          i.fa.fa-sitemap
                          |  #{truncate(a.domain, length: 35, omission: '...')}
                  li
                    = link_to 'New Site', new_account_path

app/views/hicube/base/_navigation.html.slim
section.content-header
  h1
    | #{t(heading)}
    small
      | #{t(subheading) unless subheading.nil? }
  ol.breadcrumb
    li
      a href=root_path
        i.fa.fa-dashboard
        |  Home
    - breadcrumbs.each do |k,v|
      li class=v[:active]
        - if v[:path].nil?
          = t(k)
        - else
          = link_to t(k), v[:path]

app/views/hicube/base/_sidebar.html.slim
section.sidebar
  / .user-panel
  /   .pull-left.image
  /     = image_tag 'avatar.png', alt: "User Image", class: 'img-circle'
  /   .pull-left.info
  /     p
  /       | Hello, #{current_user.name}
  /     a[href="#"]
  /       i.fa.fa-circle.text-success
  /       |  Online
  form.sidebar-form[action="#" method="get"]
    .input-group
      input.form-control[type="text" name="q" placeholder="Search..."]
      span.input-group-btn
        button#search-btn.btn.btn-flat[type="submit" name="search"]
          i.fa.fa-search
  ul.sidebar-menu
    li.header NAVIGATION
    / li.treeview class=(sidebar_class(:new, :page) || sidebar_class(:edit, :page) || sidebar_class(:index, :page) || sidebar_class(:show, :page) || sidebar_class(:edit, :page_content) || sidebar_class(:new, :page_content))
    li.treeview class=(sidebar_class(:new, :page) || sidebar_class(:edit, :page) || sidebar_class(:index, :page) || sidebar_class(:show, :page))
      a href="#"
        i.fa.fa-file-code-o
        span
          = t 'pages'
        i.fa.fa-angle-left.pull-right
      ul.treeview-menu
        / li class=sidebar_class(:index, :page)
        /   a href=pages_path
        /     i.fa.fa-angle-double-right
        /     = t 'All'
        - current_account.pages.unscoped.parents.each do |p|
          - unless p.junction?
            li class=(sidebar_class(:edit, :page, p) || sidebar_class(:show, :page, p))
              a href=edit_page_path(p)
                i.fa.fa-angle-double-right
                = p
          - else
            li class=(sidebar_class(:edit, :page, p) || sidebar_class(:show, :page, p) || ((@page.nil? || @page.parent != p) ? false : sidebar_class(:edit, :page)))
              a href="#"
                i.fa.fa-angle-double-right
                = p
                i.fa.fa-angle-left.pull-right
              ul.treeview-menu
                li class=(sidebar_class(:edit, :page, p) || sidebar_class(:show, :page, p))
                  a href=edit_page_path(p)
                    i.fa.fa-circle-o
                    = p
                - p.children.each do |c|
                  li class=(sidebar_class(:edit, :page, c) || sidebar_class(:show, :page, c))
                    a href=edit_page_path(c)
                      i.fa.fa-circle-o
                      = c 

        li class=sidebar_class(:new, :page)
          a href=new_page_path
            i.fa.fa-angle-double-right
            = t 'new_page'
        / - unless sidebar_class(:edit, :page).nil? and sidebar_class(:show, :page).nil?
        /   li class=(sidebar_class(:edit, :page) or sidebar_class(:show, :page))
        /     a href=""
        /       i.fa.fa-circle-o
        /       = @page
        
    li.treeview class=(sidebar_class(:new, :snippet) || sidebar_class(:edit, :snippet) || sidebar_class(:index, :snippet) || sidebar_class(:show, :snippet))
      a href="#"
        i.fa.fa-code
        span
          | Snippets
        i.fa.fa-angle-left.pull-right
      ul.treeview-menu
        / li class=sidebar_class(:index, :snippet)
        /   a href=snippets_path
        /     i.fa.fa-angle-double-right
        /     = t 'list'
        - current_account.snippets.each do |s|
          li class=(sidebar_class(:edit, :snippet, s) || sidebar_class(:show, :snippet, s))
            a href=edit_snippet_path(s)
              i.fa.fa-angle-double-right
              = s
        li class=sidebar_class(:new, :snippet)
          a href=new_snippet_path
            i.fa.fa-angle-double-right
            = t 'new'
        / - unless sidebar_class(:edit, :snippet).nil? and sidebar_class(:show, :page).nil?
        /   li class=(sidebar_class(:show, :snippet) or sidebar_class(:edit, :snippet))
        /     a href=""
        /       i.fa.fa-angle-double-right
        /       = @snippet

    li.treeview class=(sidebar_class(:new, :document) || sidebar_class(:edit, :document) || sidebar_class(:index, :document) || sidebar_class(:show, :document))
      a href="#"
        i.fa.fa-picture-o
        span
          | Documents
        i.fa.fa-angle-left.pull-right
      ul.treeview-menu
        li class=sidebar_class(:index, :document)
          a href=documents_path
            i.fa.fa-angle-double-right
            = t 'list'
        li class=sidebar_class(:new, :document)
          a href=new_document_path
            i.fa.fa-angle-double-right
            = t 'new'
        - unless sidebar_class(:edit, :document).nil? and sidebar_class(:show, :document).nil?
          li class=(sidebar_class(:show, :document) or sidebar_class(:edit, :document))
            a href=""
              i.fa.fa-angle-double-right
              = @document
    li.treeview class=(sidebar_class(:edit, :account, Hicube::Account.first) || sidebar_class(:show, :account, Hicube::Account.first) || sidebar_class(:new, :account))
      a href=account_path(Hicube::Account.first)
        i.fa.fa-cogs
        span
          | Settings
        / i.fa.fa-angle-left.pull-right
      / ul.treeview-menu
      /   li class=(sidebar_class(:edit, :account) || sidebar_class(:show, :account) || sidebar_class(:new, :account))
      /     a href=(Hicube::Account.first.nil? ? new_account_path : account_path(Hicube::Account.first))
      /       i.fa.fa-angle-double-right
      /       = t 'account'

    = yield :sidebar_menu